### ISSUE TITLE
API to use the generated certificates 

### ISSUE THREAD

**Issue by onerinas** [daquinoaldo/https-localhost#20]
**How would you like to expand the functionalities?**
Ability to generate and use certs directly for the existing server

**Are there alternatives?**
- Alternative is to use express app included in htttps-localhost but it cannot be used in cases like socket since app.listen won't work.
https://socket.io/docs/#Using-with-Express
- Another alternative is to use [mkcert](https://github.com/FiloSottile/mkcert) directly to generate the cert. This is an extra step to download the certs whereas https-localhost does that automatically and developer doesn't have to run commands for that

**Is it a breaking change?**
Probably yes, depending upon what would be resulting API when this feature is implemented

**Comment by daquinoaldo** [comment]
Hi @onerinas!

Take a look to the [`getCerts()`](https://github.com/daquinoaldo/https-localhost/blob/master/certs.js#L121) functions. I could try to make it available programmatically.
Then you can start the server with `https.createServer(await getCerts(), app).listen(port)`

Otherwise, we can add a parameter to the [`createServer()`](https://github.com/daquinoaldo/https-localhost/blob/master/index.js#L15) or the [`listen()`](https://github.com/daquinoaldo/https-localhost/blob/master/index.js#L20) functions to pas the `app`, but I'm not sure that cover all the possibilities. Probably a lambda would be better but at this point providing `getCerts()` would be more or less the same.

**Comment by onerinas** [comment]
No problem at all, enjoy your trip and thank you for the quick response! 

>Then you can start the server with https.createServer(await getCerts(), app).listen(port)
Yes, I was hoping for something like that.

**Comment by daquinoaldo** [comment]
Fine, next weekend I'll try to rearrange the structure to expose `getCerts()` 👌

**Comment by onerinas** [comment]
I've forked the repo to use in our project. Here is the commit: https://github.com/onerinas/https-localhost/commit/ae6386ebc282c50c0a0989925bcb5e4273192090

usage:
`https.createServer(await httpsLocalhost.getCerts(), app)`

I don't have any tests to create a PR here.

**Comment by daquinoaldo** [comment]
Hi @onerinas,
I checked your PR #22 but contains breaking changes.

In particular, it changes the current use from
```javascript
const httpsLocalhost = require("https-localhost")
const app = httpsLocalhost()
```
to
```javascript
const httpsLocalhost = require("https-localhost").app
const app = httpsLocalhost()
```

Actually, I won't push a breaking change now. Maybe in the future, but I will totally remove express in that case.

I've created a [branch](https://github.com/daquinoaldo/https-localhost/tree/getCerts) that should solve your problem.

I paste an example for clarity:
```javascript
const httpsLocalhost = require("https-localhost")()
// const app = ...
// const port = 443
const certs = await httpsLocalhost.getCerts()
const server = https.createServer(certs, app).listen(port)
```

Let me know if this solution can work for you.

**Comment by onerinas** [comment]
Yes, this would work!

**Comment by daquinoaldo** [comment]
Fine!

I'll publish it in the next few days together with other changes.
