### ISSUE TITLE
[Windows] keytool error: java.lang.Exception: Keystore file does not exist

### ISSUE THREAD

**Issue by RezaErfani67** [daquinoaldo/https-localhost#26]
![image](https://user-images.githubusercontent.com/24381986/64919870-5e2c4700-d7c5-11e9-855d-9cdba90a0f86.png)

**Comment by daquinoaldo** [comment]
Hi!
This is a problem with [mkcert](https://github.com/FiloSottile/mkcert) that is used to generate certificates.  The problem is that mkcert is not able to add the key to your Java Keystore file.

1. Is Java installed properly on your PC?
2. First run of https-localhost should be under a privileged shell: open the shell with Win + X > Power Shell (Admin), then execute https-localhost. You may need the `REINSTALL=true` option.

Let me know if that works. Otherwise, can you show me with which command you run https-localhost and in which shell?

**Comment by RezaErfani67** [comment]
thanks for quick response...
1- i install java for android studio and is OK 
2- i run below command  from command prompt with "run as administrator" privilege...
```
nodemon app.js
```
maybe the problem is from my system...
no matter... 
i close this issue
thank you mr
