### ISSUE TITLE
Can this run in limited environment likes Electron, in Android and iOS through ReactNative?

### ISSUE THREAD

**Issue by linonetwo** [daquinoaldo/https-localhost#34]
I'd like to make a portable BaaS server with this, so a user can open an Android app or cross-platform electron app to start an https server.

I'm wondering if it is possible to do so. Maybe it is up to `appdata-path`, it doesn't work in the mobile environment.

**Comment by daquinoaldo** [comment]
Hi @linonetwo 
I'm not sure I understand your aim: you want to allow users to visit a website on https://localhost from a mobile browser (e.g. Chrome) or you want to encapsulate this service in an app that also shows the website by itself?

As you said, probably `appdata-path` could be a problem, but a workaround should not be difficult.
The main issue you have to take into account is that https-localhost requires sudo permissions to add and trust a self-generated certification authority.
You can bypass the sudo requirement if you don't need a trusted certificate. In that case, you may be interested in rewrite it by yourself since it will be like 3 lines of code plus a non-signed self-generated certificate.
