### ISSUE TITLE
RangeError: Invalid typed array length: -4095

### ISSUE THREAD

**Issue by asos-albinotonnina** [daquinoaldo/https-localhost#35]
**Bug description**
As you stated in the README, I'm getting this error only when `ENV=production`. 
I do need that because I'm trying this tool, which looks great, for performance tests.
Reason why I'm opening this issue is that I'm running node 12.14, which is fairly new!

**To Reproduce**

server.js
```javascript
const app = require("https-localhost")();
app.get("/", function(req, res) {
  res.send(`hello, http2`);
});

app.listen(4000);

```

```javascript
NODE_ENV=production node ./server.js
```

**Expected behavior**
not `RangeError: Invalid typed array length: -4095`

**System information (please complete the following information):**
 - OS: MacOS Catalina
 - App version 4.4.1
 - Node version 12.14

**Comment by daquinoaldo** [comment]
Hi @asos-albinotonnina!

This is a [known bug](https://github.com/spdy-http2/node-spdy/issues/363) of the spdy library. This is the reason I don't use http2 by default but only in production mode. Unfortunately, there aren't any news about a possible fix neither we know under which conditions it occurs. I'm not able to reproduce the bug to fix the library.

At the moment, the only fix is to avoid the production environment. If you need production in you context you can workaround in the following way.
```js
const nodeEnv = process.env.NODE_ENV;
process.env.NODE_ENV = "development";
const app = require("https-localhost")();
process.env.NODE_ENV = nodeEnv;
```

In version 5 of https-localhost I planned to stop using express. This will allow to use the new built-in http2 instead of spdy, since express doesn't support http2 yet.
Hopefully, v5 should come in March 2020.

If you don't need express either, take a look to [Use with a web framework different from Express.js](https://github.com/daquinoaldo/https-localhost/blob/master/README.md#use-with-a-web-framework-different-from-expressjs). Just use http2 instead of https in the example code. 
There are no changes that you can use express in this way, but take a look to koajs, it should work and it is newer and lighter.


_Feel free to reopen this issue if my answer does not satisfy your questions_
