### ISSUE TITLE
localhost didn’t send any data. 

### ISSUE THREAD

**Issue by williamsokol** [daquinoaldo/https-localhost#61]
**Bug description**
I have tried to make this run on 2 different Windows computers with different node versions and both got the same error "localhost didn’t send any data." I used npm to download it using the command "npm i -g --only=prod https-localhost". This happens to websites that do work with normal local hosting in python and node.js.

**To Reproduce**
1. download node.js on windows
2. use "npm i -g --only=prod https-localhost"
3. type 'serve' in dirctory with index.html file
4. go to local host url

**Expected behavior**
I expected the website to be running as it would on standard localhost

**System information (please complete the following information):**
 - OS:  Windows 10 and Windows 7
 - App version: node v14.16.0 and v13.14.0

**Additional context**
I would think it could be because I had the standard local host serve and they both use 'serve' as their command but I only had local host on the Windows 10

**Comment by daquinoaldo** [comment]
Hi @williamsokol, I’m not sure to understand correctly.
After `npm i -g https-localhost` have you run `serve .` in a directory with static html files?

**Comment by williamsokol** [comment]
Oops, I did "serve" in my directory on terminal, didn't add that bit. The file I was serving is this guys repo: https://github.com/Web3Modal/web3modal-vanilla-js-example where they actually recommend we use your package so I think it should be working.

**Comment by daquinoaldo** [comment]
The content is fine. You should be either inside the directory or specify the directory path.
Can’t you see the files in https://localhost or have you a connection security error? In the latter case, try run a terminal as administrator the first time you run `serve`. It needs it to create the certificate and add it as trust in the system. Subsequent attempt doesn’t need to be run on an administrator terminal since the certificate already exists.
